project:
  type: website

website:
  title: "lang-dev-bridge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    lang: zh-cn

execute:
  freeze: true
